import = [
  "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[scrolling]
history = 100000

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach || zellij"]
