import = [
  # "/home/sahir/.config/alacritty/catppuccin-mocha.toml"
  "/home/sahir/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10 

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[scrolling]
history = 100000

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
